CREATE TABLE company (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id SERIAL PRIMARY KEY,
    company_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    dosage TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE comment (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL,
    author_name TEXT NOT NULL,
    author_email TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO company (name) VALUES
    ('Laboratório Vale Verde'),
    ('Farmacêutica Serra Azul'),
    ('Instituto Farmacêutico Aurora'),
    ('Laboratórios Piatã'),
    ('BioNorte Farmacêutica'),
    ('Farmoquímica Recôncavo'),
    ('Laboratório Santa Clara do Sul'),
    ('Vitalis Indústria Farmacêutica'),
    ('Farmacêutica Ipiranga do Norte'),
    ('Laboratório Caatinga Bio'),
    ('Sertão Farma Indústria'),
    ('Meridiano Laboratórios');

INSERT INTO product (company_id, name, description, price, dosage) VALUES
    (1, 'Dipirona Sódica', 'Analgésico e antitérmico em comprimidos, caixa com 20 unidades.', 12.90, '500 mg'),
    (1, 'Paracetamol', 'Analgésico e antitérmico em comprimidos, caixa com 20 unidades.', 10.40, '750 mg'),
    (1, 'Ibuprofeno', 'Anti-inflamatório não esteroidal em comprimidos revestidos, caixa com 30 unidades.', 21.75, '400 mg'),
    (1, 'Amoxicilina', 'Antibiótico de amplo espectro em cápsulas, caixa com 21 unidades.', 38.50, '500 mg'),
    (1, 'Omeprazol', 'Inibidor de bomba de prótons em cápsulas de liberação retardada, caixa com 28 unidades.', 18.60, '20 mg'),
    (1, 'Losartana Potássica', 'Anti-hipertensivo antagonista da angiotensina II, caixa com 30 comprimidos.', 16.20, '50 mg'),
    (1, 'Metformina', 'Antidiabético oral de liberação imediata, caixa com 30 comprimidos revestidos.', 14.80, '850 mg'),
    (1, 'Loratadina', 'Antialérgico não sedativo em comprimidos, caixa com 12 unidades.', 11.30, '10 mg'),
    (2, 'Dipirona Sódica Gotas', 'Analgésico e antitérmico em solução oral, frasco com 20 mL.', 9.70, '500 mg/mL'),
    (2, 'Diclofenaco Sódico', 'Anti-inflamatório em comprimidos gastrorresistentes, caixa com 20 unidades.', 15.40, '50 mg'),
    (2, 'Azitromicina', 'Antibiótico macrolídeo em comprimidos revestidos, caixa com 5 unidades.', 42.90, '500 mg'),
    (2, 'Pantoprazol', 'Inibidor de bomba de prótons em comprimidos revestidos, caixa com 28 unidades.', 26.50, '40 mg'),
    (2, 'Enalapril', 'Anti-hipertensivo inibidor da ECA, caixa com 30 comprimidos.', 13.90, '10 mg'),
    (2, 'Sinvastatina', 'Redutor de colesterol da classe das estatinas, caixa com 30 comprimidos revestidos.', 19.80, '20 mg'),
    (2, 'Fluoxetina', 'Antidepressivo inibidor seletivo da recaptação de serotonina, caixa com 30 cápsulas.', 22.40, '20 mg'),
    (3, 'Paracetamol Infantil', 'Analgésico e antitérmico em suspensão oral, frasco com 100 mL.', 13.20, '32 mg/mL'),
    (3, 'Nimesulida', 'Anti-inflamatório em comprimidos, caixa com 12 unidades.', 17.60, '100 mg'),
    (3, 'Cefalexina', 'Antibiótico cefalosporínico em cápsulas, caixa com 8 unidades.', 34.70, '500 mg'),
    (3, 'Domperidona', 'Procinético para refluxo e náusea, caixa com 30 comprimidos.', 20.10, '10 mg'),
    (3, 'Anlodipino', 'Anti-hipertensivo bloqueador de canal de cálcio, caixa com 30 comprimidos.', 12.70, '5 mg'),
    (3, 'Levotiroxina Sódica', 'Reposição hormonal tireoidiana, caixa com 30 comprimidos.', 24.30, '50 mcg'),
    (4, 'Ibuprofeno', 'Anti-inflamatório não esteroidal em comprimidos revestidos, caixa com 20 unidades.', 25.90, '600 mg'),
    (4, 'Ciprofloxacino', 'Antibiótico fluoroquinolônico em comprimidos revestidos, caixa com 14 unidades.', 46.80, '500 mg'),
    (4, 'Ranitidina', 'Antagonista H2 para acidez gástrica, caixa com 20 comprimidos revestidos.', 16.90, '150 mg'),
    (4, 'Atenolol', 'Betabloqueador anti-hipertensivo, caixa com 30 comprimidos.', 11.60, '25 mg'),
    (4, 'Glibenclamida', 'Antidiabético oral sulfonilureia, caixa com 30 comprimidos.', 10.90, '5 mg'),
    (4, 'Sertralina', 'Antidepressivo inibidor seletivo da recaptação de serotonina, caixa com 30 comprimidos.', 31.50, '50 mg'),
    (5, 'Cetoprofeno', 'Anti-inflamatório em cápsulas, caixa com 10 unidades.', 23.40, '100 mg'),
    (5, 'Claritromicina', 'Antibiótico macrolídeo em comprimidos revestidos, caixa com 10 unidades.', 58.20, '500 mg'),
    (5, 'Bromoprida', 'Antiemético e procinético em cápsulas, caixa com 20 unidades.', 18.30, '10 mg'),
    (5, 'Propranolol', 'Betabloqueador para hipertensão e enxaqueca, caixa com 30 comprimidos.', 10.20, '40 mg'),
    (5, 'Salbutamol', 'Broncodilatador em aerossol para asma, frasco com 200 doses.', 29.90, '100 mcg'),
    (6, 'Naproxeno', 'Anti-inflamatório de ação prolongada, caixa com 15 comprimidos revestidos.', 27.60, '550 mg'),
    (6, 'Metronidazol', 'Antibiótico e antiprotozoário em comprimidos, caixa com 20 unidades.', 19.40, '400 mg'),
    (6, 'Simeticona', 'Antiflatulento em cápsulas gelatinosas, caixa com 30 unidades.', 14.10, '40 mg'),
    (6, 'Hidroclorotiazida', 'Diurético tiazídico anti-hipertensivo, caixa com 30 comprimidos.', 9.80, '25 mg'),
    (6, 'Budesonida', 'Corticoide inalatório para asma persistente, frasco com 120 doses.', 52.70, '200 mcg'),
    (7, 'Meloxicam', 'Anti-inflamatório seletivo COX-2, caixa com 10 comprimidos.', 21.30, '15 mg'),
    (7, 'Nitrofurantoína', 'Antibiótico para infecção urinária em cápsulas, caixa com 28 unidades.', 39.60, '100 mg'),
    (7, 'Atorvastatina', 'Redutor de colesterol da classe das estatinas, caixa com 30 comprimidos revestidos.', 28.40, '20 mg'),
    (7, 'Cetirizina', 'Antialérgico de segunda geração, caixa com 12 comprimidos revestidos.', 15.70, '10 mg'),
    (7, 'Aciclovir', 'Antiviral para herpes em comprimidos, caixa com 25 unidades.', 33.20, '200 mg'),
    (8, 'Prednisona', 'Corticoide oral em comprimidos, caixa com 20 unidades.', 18.90, '20 mg'),
    (8, 'Sulfametoxazol + Trimetoprima', 'Antibiótico combinado em comprimidos, caixa com 20 unidades.', 22.80, '800 mg + 160 mg'),
    (8, 'Rosuvastatina', 'Redutor de colesterol de alta potência, caixa com 30 comprimidos revestidos.', 41.50, '10 mg'),
    (8, 'Fexofenadina', 'Antialérgico não sedativo, caixa com 10 comprimidos revestidos.', 26.10, '120 mg'),
    (9, 'Diclofenaco Potássico', 'Anti-inflamatório de absorção rápida, caixa com 20 comprimidos revestidos.', 16.80, '50 mg'),
    (9, 'Dexametasona', 'Corticoide de alta potência em comprimidos, caixa com 10 unidades.', 15.20, '4 mg'),
    (9, 'Gliclazida', 'Antidiabético oral de liberação modificada, caixa com 30 comprimidos.', 27.90, '30 mg'),
    (9, 'Fluconazol', 'Antifúngico em cápsula de dose única, caixa com 1 unidade.', 19.70, '150 mg'),
    (10, 'Paracetamol', 'Analgésico e antitérmico em comprimidos, caixa com 20 unidades.', 8.90, '500 mg'),
    (10, 'Dexclorfeniramina', 'Antialérgico sedativo em comprimidos, caixa com 20 unidades.', 12.40, '2 mg'),
    (10, 'Amitriptilina', 'Antidepressivo tricíclico, caixa com 20 comprimidos revestidos.', 17.30, '25 mg'),
    (10, 'Sulfato Ferroso', 'Suplemento de ferro para anemia, caixa com 30 comprimidos revestidos.', 11.80, '40 mg'),
    (11, 'Cetoconazol', 'Antifúngico oral em comprimidos, caixa com 10 unidades.', 24.60, '200 mg'),
    (11, 'Clonazepam', 'Ansiolítico e anticonvulsivante, caixa com 30 comprimidos.', 20.50, '2 mg'),
    (11, 'Ácido Fólico', 'Suplemento vitamínico para gestantes, caixa com 30 comprimidos.', 13.60, '5 mg'),
    (12, 'Dimenidrinato', 'Antiemético para enjoo e labirintite, caixa com 20 comprimidos.', 16.40, '100 mg'),
    (12, 'Escitalopram', 'Antidepressivo inibidor seletivo da recaptação de serotonina, caixa com 30 comprimidos.', 44.80, '10 mg'),
    (12, 'Carbonato de Cálcio', 'Suplemento de cálcio com vitamina D, caixa com 60 comprimidos.', 29.30, '600 mg + 400 UI');

INSERT INTO comment (product_id, author_name, author_email, content) VALUES
    (1, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Funciona, mas o gosto amargo é difícil de disfarçar.'),
    (1, 'Larissa Quadros', 'larissa.quadros@exemplo.com', 'Cortou a febre do meu filho durante a noite toda.'),
    (1, 'Leandro Piedade', 'leandro.piedade@exemplo.com', 'Bem mais barato que a versão de marca e o efeito é o mesmo.'),
    (1, 'Renata Bulhões', 'renata.bulhoes@exemplo.com', 'Alívio rápido para dor de cabeça, faz efeito em uns vinte minutos.'),
    (1, 'Sofia Andrade', 'sofia.andrade@exemplo.com', 'Comprimido grande demais, tenho dificuldade para engolir.'),
    (1, 'Helena Vasconcelos', 'helena.vasconcelos@exemplo.com', 'Levo sempre na bolsa, nunca me deixou na mão em enxaqueca.'),
    (1, 'Rogério Bastos', 'rogerio.bastos@exemplo.com', 'Uso para dor nas costas e resolve bem, sem me deixar sonolento.'),
    (1, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Já é a terceira vez que compro desse laboratório, sempre confiável.'),
    (2, 'Gustavo Rabelo', 'gustavo.rabelo@exemplo.com', 'Para dor de dente não segurou tanto quanto eu esperava.'),
    (2, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Funciona, mas o gosto amargo é difícil de disfarçar.'),
    (2, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Bem mais barato que a versão de marca e o efeito é o mesmo.'),
    (2, 'André Lousada', 'andre.lousada@exemplo.com', 'Levo sempre na mochila, nunca me deixou na mão em enxaqueca.'),
    (2, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Alívio rápido para dor de cabeça, faz efeito em uns vinte minutos.'),
    (2, 'Ricardo Portela', 'ricardo.portela@exemplo.com', 'Cortou a febre do meu filho durante a noite toda.'),
    (2, 'Otávio Bandeira', 'otavio.bandeira@exemplo.com', 'Uso para a dor do corpo na gripe e resolve bem, sem me deixar sonolento.'),
    (2, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'A bula veio amassada, mas o produto estava íntegro.'),
    (3, 'Rogério Bastos', 'rogerio.bastos@exemplo.com', 'Para tendinite funcionou melhor que os anteriores que usei.'),
    (3, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Precisei tomar junto com protetor gástrico, senão azia forte.'),
    (3, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Desinchou meu joelho em dois dias de tratamento.'),
    (3, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Já é a terceira vez que compro desse laboratório, sempre confiável.'),
    (4, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Tratamento completo em sete dias, exatamente como o médico indicou.'),
    (4, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'Deu bastante desconforto intestinal, tive que tomar probiótico junto.'),
    (4, 'Ricardo Portela', 'ricardo.portela@exemplo.com', 'Caro, mas foi o único que funcionou no meu caso.'),
    (4, 'Rogério Bastos', 'rogerio.bastos@exemplo.com', 'A cartela vem lacrada e a caixa tem o lote impresso legível.'),
    (5, 'Aline Furtado', 'aline.furtado@exemplo.com', 'Resolveu a azia da gravidez, que não me deixava dormir.'),
    (5, 'Rogério Bastos', 'rogerio.bastos@exemplo.com', 'Ajudou com a queimação depois das refeições.'),
    (5, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Bom preço para a quantidade de cápsulas da caixa.'),
    (5, 'Leandro Piedade', 'leandro.piedade@exemplo.com', 'A bula veio amassada, mas o produto estava íntegro.'),
    (6, 'Marina Alcântara', 'marina.alcantara@exemplo.com', 'Troquei para esse por causa da tosse do anterior e me adaptei bem.'),
    (6, 'Helena Vasconcelos', 'helena.vasconcelos@exemplo.com', 'Minha pressão estabilizou em duas semanas de uso contínuo.'),
    (6, 'Bruno Tavares', 'bruno.tavares@exemplo.com', 'Uso há dois anos por indicação do cardiologista, sem efeito colateral.'),
    (6, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Senti um pouco de tontura nos primeiros dias, depois passou.'),
    (6, 'Gustavo Rabelo', 'gustavo.rabelo@exemplo.com', 'Comprimido pequeno e fácil de partir ao meio quando preciso.'),
    (6, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Entrega demorou mais do que o previsto, mas o produto está correto.'),
    (7, 'Renata Bulhões', 'renata.bulhoes@exemplo.com', 'Controle bom, mas precisa de acompanhamento médico de perto.'),
    (8, 'Marina Alcântara', 'marina.alcantara@exemplo.com', 'Acabou com a coceira da urticária em poucas horas.'),
    (8, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Não me dá sono, consigo tomar de manhã e trabalhar normalmente.'),
    (10, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Bom para dor muscular pós-treino, sem irritar o estômago.'),
    (11, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Resolveu minha sinusite com apenas cinco comprimidos.'),
    (12, 'Marina Alcântara', 'marina.alcantara@exemplo.com', 'Cortou a queimação que eu sentia depois do almoço.'),
    (12, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Acabou com a azia que eu tinha todas as manhãs.'),
    (13, 'Sofia Andrade', 'sofia.andrade@exemplo.com', 'Provocou uma tosse seca persistente e precisei conversar com o médico.'),
    (13, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Minha pressão estabilizou em duas semanas de uso contínuo.'),
    (13, 'Márcio Damasceno', 'marcio.damasceno@exemplo.com', 'Caixa com trinta comprimidos dura o mês inteiro, prático.'),
    (14, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'Uso há dois anos por indicação do cardiologista, sem efeito colateral.'),
    (14, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Caixa com trinta comprimidos dura o mês inteiro, prático.'),
    (15, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Deu boca seca no início, mas foi o único efeito que senti.'),
    (16, 'Helena Vasconcelos', 'helena.vasconcelos@exemplo.com', 'Levo sempre na bolsa, nunca me deixou na mão na febre da minha filha.'),
    (16, 'Cristiane Aroeira', 'cristiane.aroeira@exemplo.com', 'Para a dor de dente do meu filho não segurou tanto quanto eu esperava.'),
    (17, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Para tendinite funcionou melhor que os anteriores que usei.'),
    (17, 'Ricardo Portela', 'ricardo.portela@exemplo.com', 'Meu ortopedista receitou e cumpriu exatamente o esperado.'),
    (17, 'Bruno Tavares', 'bruno.tavares@exemplo.com', 'O efeito é bom, mas me deixou com um pouco de enjoo.'),
    (19, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Tomo em jejum há três meses e o refluxo sumiu.'),
    (19, 'Aline Furtado', 'aline.furtado@exemplo.com', 'Aliviou o estômago, mas demorou uns dias para fazer efeito.'),
    (20, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Senti um pouco de tontura nos primeiros dias, depois passou.'),
    (20, 'Cristiane Aroeira', 'cristiane.aroeira@exemplo.com', 'Uso há dois anos por indicação do cardiologista, sem efeito colateral.'),
    (21, 'Larissa Quadros', 'larissa.quadros@exemplo.com', 'Precisa tomar em jejum e esperar meia hora, exige disciplina.'),
    (22, 'Otávio Bandeira', 'otavio.bandeira@exemplo.com', 'Para tendinite funcionou melhor que os anteriores que usei.'),
    (22, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Desinchou meu joelho em dois dias de tratamento.'),
    (22, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Meu ortopedista receitou e cumpriu exatamente o esperado.'),
    (22, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'A cartela vem lacrada e a caixa tem o lote impresso legível.'),
    (24, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Segurou bem a acidez da gravidez, com orientação da obstetra.'),
    (25, 'Renata Bulhões', 'renata.bulhoes@exemplo.com', 'Preço justo para uso contínuo, faz diferença no orçamento.'),
    (25, 'Bruno Tavares', 'bruno.tavares@exemplo.com', 'Comprimido pequeno e fácil de partir ao meio quando preciso.'),
    (25, 'Aline Furtado', 'aline.furtado@exemplo.com', 'Senti mais cansaço nas caminhadas, mas a pressão ficou controlada.'),
    (26, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'Minha glicemia de jejum caiu bastante no primeiro mês.'),
    (27, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Tive insônia nos primeiros dias, depois normalizou.'),
    (27, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Deu boca seca no início, mas foi o único efeito que senti.'),
    (27, 'Ricardo Portela', 'ricardo.portela@exemplo.com', 'Levou umas três semanas para fazer efeito, mas valeu a espera.'),
    (29, 'Renata Bulhões', 'renata.bulhoes@exemplo.com', 'Atenção ao horário, precisa ser de doze em doze horas certinho.'),
    (29, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Resolveu a infecção respiratória sem precisar trocar de medicação.'),
    (30, 'Aline Furtado', 'aline.furtado@exemplo.com', 'Bom preço para a quantidade de cápsulas da caixa.'),
    (31, 'Fernando Peixoto', 'fernando.peixoto@exemplo.com', 'Diminuiu bastante a frequência das minhas enxaquecas.'),
    (33, 'Helena Vasconcelos', 'helena.vasconcelos@exemplo.com', 'Bom para dor muscular pós-treino, sem irritar o estômago.'),
    (34, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Resolveu a infecção intestinal sem precisar trocar de medicação.'),
    (34, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Tomo de oito em oito horas certinho, como o médico orientou.'),
    (34, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Tratamento completo em sete dias, exatamente como o médico indicou.'),
    (35, 'Gustavo Rabelo', 'gustavo.rabelo@exemplo.com', 'Acabou com o excesso de gases depois das refeições.'),
    (38, 'Larissa Quadros', 'larissa.quadros@exemplo.com', 'O efeito é bom, mas me deixou com um pouco de enjoo.'),
    (39, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Resolveu a infecção urinária sem precisar trocar de medicação.'),
    (39, 'Leandro Piedade', 'leandro.piedade@exemplo.com', 'Deu bastante desconforto intestinal, tive que tomar probiótico junto.'),
    (39, 'André Lousada', 'andre.lousada@exemplo.com', 'Cápsula fácil de engolir e cartela bem lacrada.'),
    (41, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Uso na época de poeira em casa e resolve na hora.'),
    (42, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Precisa tomar cinco vezes ao dia, é o único incômodo.'),
    (42, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Quanto antes começar o tratamento, melhor o resultado.'),
    (43, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Ciclo curto conforme receita, resolveu a crise alérgica.'),
    (44, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Cortou a infecção urinária já no segundo dia.'),
    (45, 'Helena Vasconcelos', 'helena.vasconcelos@exemplo.com', 'Meu colesterol caiu bastante já no primeiro exame de controle.'),
    (45, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Senti dor muscular nas pernas no começo e o médico ajustou a dose.'),
    (46, 'Leandro Piedade', 'leandro.piedade@exemplo.com', 'Alivia a alergia sem me dar sono, tomo antes do trabalho.'),
    (46, 'Renata Bulhões', 'renata.bulhoes@exemplo.com', 'Caixa pequena para o preço, dura pouco mais de uma semana.'),
    (46, 'Sofia Andrade', 'sofia.andrade@exemplo.com', 'Uso na época de poeira em casa e resolve na hora.'),
    (47, 'Vanessa Tinoco', 'vanessa.tinoco@exemplo.com', 'Bom para dor muscular pós-treino, sem irritar o estômago.'),
    (47, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Ajudou muito na dor lombar depois de uma semana de uso.'),
    (48, 'Larissa Quadros', 'larissa.quadros@exemplo.com', 'Funcionou bem para a crise de bronquite do meu filho.'),
    (48, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Ciclo curto conforme receita, resolveu a crise alérgica.'),
    (49, 'Sofia Andrade', 'sofia.andrade@exemplo.com', 'Precisei ajustar o horário para não ter queda de açúcar, depois estabilizou.'),
    (51, 'Tiago Moreira', 'tiago.moreira@exemplo.com', 'Para dor de dente não segurou tanto quanto eu esperava.'),
    (51, 'Gustavo Rabelo', 'gustavo.rabelo@exemplo.com', 'Alívio rápido para dor de cabeça, faz efeito em uns vinte minutos.'),
    (51, 'Cristiane Aroeira', 'cristiane.aroeira@exemplo.com', 'Bem mais barato que a versão de marca e o efeito é o mesmo.'),
    (51, 'Camila Rezende', 'camila.rezende@exemplo.com', 'Uso para cólica e resolve bem, sem me deixar sonolenta.'),
    (51, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Funciona, mas o gosto amargo é difícil de disfarçar.'),
    (51, 'Henrique Vilela', 'henrique.vilela@exemplo.com', 'Validade curta, faltavam oito meses quando chegou.'),
    (52, 'Gustavo Rabelo', 'gustavo.rabelo@exemplo.com', 'Esse me dá muito sono, só consigo tomar à noite.'),
    (52, 'Márcio Damasceno', 'marcio.damasceno@exemplo.com', 'Acabou com a coceira da urticária em poucas horas.'),
    (52, 'Aline Furtado', 'aline.furtado@exemplo.com', 'A caixa dura pouco mais de uma semana, mas o preço compensa.'),
    (54, 'Juliana Sampaio', 'juliana.sampaio@exemplo.com', 'Recomendado pela obstetra, tomo desde o primeiro trimestre.'),
    (56, 'André Lousada', 'andre.lousada@exemplo.com', 'Fez efeito já na primeira noite, mas uso só com receita.'),
    (57, 'Beatriz Nogueira', 'beatriz.nogueira@exemplo.com', 'Comprimido grande, mas dá para partir sem dificuldade.'),
    (57, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'Bom custo-benefício para uso diário prolongado.'),
    (58, 'Márcio Damasceno', 'marcio.damasceno@exemplo.com', 'Tomo antes de viagem longa e não passo mal no carro.'),
    (58, 'Eduardo Serpa', 'eduardo.serpa@exemplo.com', 'Cortou a tontura da labirintite em pouco tempo.'),
    (59, 'Marina Alcântara', 'marina.alcantara@exemplo.com', 'Levou umas três semanas para fazer efeito, mas valeu a espera.'),
    (59, 'Patrícia Goulart', 'patricia.goulart@exemplo.com', 'Melhorei bastante o sono e a disposição durante o dia.');
